import { describe, expect, it } from "bun:test";

describe("Integration", () => {
  it("schema generated by GraphQL Kotlin should match expected", async () => {
    const generatedSchema = await Bun.file(
      `${process.cwd()}/build/schema.graphql`,
    ).text();
    const expectedSchema = await Bun.file(
      `${process.cwd()}/test/integration/expected.graphql`,
    ).text();
    expect(generatedSchema).toBe(expectedSchema);
  });
});
