name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install Dependencies
        run: bun install

      - name: Run Prettier
        run: bun format-check

      - name: Lint
        run: bun lint

      - name: Type Check
        run: bun tsc

      - name: Unit Tests
        run: bun unit

      - uses: actions/setup-java@v5
        with:
          distribution: adopt
          java-version: 24

      - name: Integration Test
        run: bun integration

      - name: Build Docs
        run: bun docs:build
